### ISSUE TITLE
Invalid CSS for big play button

### ISSUE THREAD

**Issue by derwaldgeist** [mmcc/videojs-themes#6]
The themes for the big play buttons contain invalid CSS syntax like this:

```css
background: svg-load('icons/play-btn.svg', fill=#6fb04e);
```

I guess this is meant to be transformed by this post-processor:
https://github.com/TrySound/postcss-inline-svg
but it isn't.

**Comment by mmcc** [comment]
Ah sorry, the Readme should be more clear that if you want to use these directly from the repo you need to run `yarn build` first and use the `dist` folder, which is what the CDN versions and NPM contain.
